# Generated by Django 2.1.1 on 2018-10-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('header_image', models.ImageField(blank=True, upload_to='header_image')),
                ('text', models.TextField(blank=True)),
                ('category', models.TextField(blank=True)),
            ],
        ),
    ]
